---
- name: DEPLOY AS3 DECLARATION
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - ../../creds/big_creds.yaml

  vars:

  tasks:

  - name: Push AS3 Config to F5
    uri:
      url: https://18.133.35.147/mgmt/shared/appsvcs/declare/
      method: POST
      user: "{{bigip_user}}"
      password: "{{bigip_pass}}"
      body: "{{ lookup('file','as3.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no

...